;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from cjvmacs-ai.el

(register-definition-prefixes "cjvmacs-ai" '("cjv/ai-map"))


;;; Generated autoloads from cjvmacs-editor.el

(register-definition-prefixes "cjvmacs-editor" '("cjv/toggle-parens"))


;;; Generated autoloads from cjvmacs-keybindings.el

(register-definition-prefixes "cjvmacs-keybindings" '("cjv/"))


;;; Generated autoloads from cjvmacs-org.el

(register-definition-prefixes "cjvmacs-org" '("cjv/org-capture-place-template-dont-delete-windows"))


;;; Generated autoloads from cjvmacs-spacebase.el

(register-definition-prefixes "cjvmacs-spacebase" '("cjv/spacebase-map" "spacebase/"))


;;; Generated autoloads from cjvmacs-ui.el

(register-definition-prefixes "cjvmacs-ui" '("cjv/theme"))


;;; Generated autoloads from cjvmacs-utils.el

(register-definition-prefixes "cjvmacs-utils" '("cjv/"))

;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
